# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/peridot-miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/peridot-miuicamera

PRODUCT_PACKAGES += \
    libcamera_algoup_jni.xiaomi \
    libcamera_mianode_jni.xiaomi \
    libgui-xiaomi \
    libmicampostproc_client \
    vendor.xiaomi.hardware.campostproc@1.0_system \
    MiuiCamera
